### ISSUE TITLE
Kafka Consumer will throw ConcurrentModificationException on invoking close().

### ISSUE THREAD

**Issue by srinivasev** [payara/Cloud-Connectors#64]
Deployed RA in Wildfly. The E2E works fine,

During Wildfly server stop, consumer.close() in KafkaPoller stop() method throwing below error. Please look into this.

2019-01-30 12:31:14,212 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 6) WFLYCTL0190: Step handler org.jboss.as.server.operations.ServerShutdownHandler$1@1a950b3c for operation {"operation" => "shutdown","operation-headers" => {"caller-type" => "user","access-mechanism" => "NATIVE"},"address" => undefined} at address [] failed handling operation rollback -- java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access: java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2215)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2104)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2059)
	at com.nokia.aor.channel.kafka.inbound.api.KafkaPoller.stop(KafkaPoller.java:61)
	at com.nokia.aor.channel.kafka.inbound.ra.KafkaInboundResourceAdapter.endpointDeactivation(KafkaInboundResourceAdapter.java:79)
	at org.jboss.jca.core.rar.EndpointImpl.deactivate(EndpointImpl.java:255)
	at org.jboss.as.ejb3.component.messagedriven.MessageDrivenComponent.deactivate(MessageDrivenComponent.java:278)
	at org.jboss.as.ejb3.component.messagedriven.MessageDrivenComponent.access$100(MessageDrivenComponent.java:63)
	at org.jboss.as.ejb3.component.messagedriven.MessageDrivenComponent$1.preSuspend(MessageDrivenComponent.java:92)
	at org.jboss.as.server.suspend.SuspendController.suspend(SuspendController.java:76)
	at org.jboss.as.server.operations.ServerShutdownHandler$1$1.handleResult(ServerShutdownHandler.java:146)
	at org.jboss.as.controller.AbstractOperationContext$Step.invokeResultHandler(AbstractOperationContext.java:1384)
	at org.jboss.as.controller.AbstractOperationContext$Step.handleResult(AbstractOperationContext.java:1366)
	at org.jboss.as.controller.AbstractOperationContext$Step.finalizeInternal(AbstractOperationContext.java:1328)
	at org.jboss.as.controller.AbstractOperationContext$Step.finalizeStep(AbstractOperationContext.java:1301)
	at org.jboss.as.controller.AbstractOperationContext$Step.access$300(AbstractOperationContext.java:1185)
	at org.jboss.as.controller.AbstractOperationContext.executeResultHandlerPhase(AbstractOperationContext.java:767)
	at org.jboss.as.controller.AbstractOperationContext.executeDoneStage(AbstractOperationContext.java:753)
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:680)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1329)
	at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:400)
	at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:222)
	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler.doExecute(ModelControllerClientOperationHandler.java:208)
	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler.access$300(ModelControllerClientOperationHandler.java:130)
	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1$1.run(ModelControllerClientOperationHandler.java:152)
	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1$1.run(ModelControllerClientOperationHandler.java:148)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.jboss.as.controller.AccessAuditContext.doAs(AccessAuditContext.java:149)
	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1.execute(ModelControllerClientOperationHandler.java:148)
	at org.jboss.as.protocol.mgmt.AbstractMessageHandler$ManagementRequestContextImpl$1.doExecute(AbstractMessageHandler.java:363)
	at org.jboss.as.protocol.mgmt.AbstractMessageHandler$AsyncTaskRunner.run(AbstractMessageHandler.java:472)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

**Comment by smillidge** [comment]
Inbound processing has been rewritten in 0.5.0 please retest when that is released.

**Comment by jGauravGupta** [comment]
Hi @srinivasev,

Cloud Connectors v0.5.0 is release, please retest and confirm.

**Comment by smillidge** [comment]
Closing due to lack of response. If you still have a problem then comment on the issue.
